/* tslint:disable */
/* eslint-disable */
/**
 * Bodoge API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Card } from './Card';
import {
    CardFromJSON,
    CardFromJSONTyped,
    CardToJSON,
    CardToJSONTyped,
} from './Card';

/**
 * 
 * @export
 * @interface CardQueue
 */
export interface CardQueue {
    /**
     * The queue of cards arranged in a specific order.
     * @type {Array<Card>}
     * @memberof CardQueue
     */
    cards?: Array<Card>;
    /**
     * this tells only the length of the queue, not the cards in it.
     * @type {number}
     * @memberof CardQueue
     */
    amount: number;
}

/**
 * Check if a given object implements the CardQueue interface.
 */
export function instanceOfCardQueue(value: object): value is CardQueue {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function CardQueueFromJSON(json: any): CardQueue {
    return CardQueueFromJSONTyped(json, false);
}

export function CardQueueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardQueue {
    if (json == null) {
        return json;
    }
    return {
        
        'cards': json['cards'] == null ? undefined : ((json['cards'] as Array<any>).map(CardFromJSON)),
        'amount': json['amount'],
    };
}

  export function CardQueueToJSON(json: any): CardQueue {
      return CardQueueToJSONTyped(json, false);
  }

  export function CardQueueToJSONTyped(value?: CardQueue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cards': value['cards'] == null ? undefined : ((value['cards'] as Array<any>).map(CardToJSON)),
        'amount': value['amount'],
    };
}

