/* tslint:disable */
/* eslint-disable */
/**
 * Bodoge API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Dummy200Response
 */
export interface Dummy200Response {
    /**
     * 
     * @type {any}
     * @memberof Dummy200Response
     */
    dummy1?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Dummy200Response
     */
    dummy2?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Dummy200Response
     */
    dummy3?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Dummy200Response
     */
    dummy4?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Dummy200Response
     */
    dummy5?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Dummy200Response
     */
    dummy6?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Dummy200Response
     */
    dummy7?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Dummy200Response
     */
    dummy8?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Dummy200Response
     */
    dummy9?: any | null;
}

/**
 * Check if a given object implements the Dummy200Response interface.
 */
export function instanceOfDummy200Response(value: object): value is Dummy200Response {
    return true;
}

export function Dummy200ResponseFromJSON(json: any): Dummy200Response {
    return Dummy200ResponseFromJSONTyped(json, false);
}

export function Dummy200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dummy200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'dummy1': json['dummy1'] == null ? undefined : json['dummy1'],
        'dummy2': json['dummy2'] == null ? undefined : json['dummy2'],
        'dummy3': json['dummy3'] == null ? undefined : json['dummy3'],
        'dummy4': json['dummy4'] == null ? undefined : json['dummy4'],
        'dummy5': json['dummy5'] == null ? undefined : json['dummy5'],
        'dummy6': json['dummy6'] == null ? undefined : json['dummy6'],
        'dummy7': json['dummy7'] == null ? undefined : json['dummy7'],
        'dummy8': json['dummy8'] == null ? undefined : json['dummy8'],
        'dummy9': json['dummy9'] == null ? undefined : json['dummy9'],
    };
}

  export function Dummy200ResponseToJSON(json: any): Dummy200Response {
      return Dummy200ResponseToJSONTyped(json, false);
  }

  export function Dummy200ResponseToJSONTyped(value?: Dummy200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dummy1': value['dummy1'],
        'dummy2': value['dummy2'],
        'dummy3': value['dummy3'],
        'dummy4': value['dummy4'],
        'dummy5': value['dummy5'],
        'dummy6': value['dummy6'],
        'dummy7': value['dummy7'],
        'dummy8': value['dummy8'],
        'dummy9': value['dummy9'],
    };
}

