/* tslint:disable */
/* eslint-disable */
/**
 * Bodoge API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GamePhase } from './GamePhase';
import {
    GamePhaseFromJSON,
    GamePhaseFromJSONTyped,
    GamePhaseToJSON,
    GamePhaseToJSONTyped,
} from './GamePhase';
import type { UIStateCode } from './UIStateCode';
import {
    UIStateCodeFromJSON,
    UIStateCodeFromJSONTyped,
    UIStateCodeToJSON,
    UIStateCodeToJSONTyped,
} from './UIStateCode';

/**
 * 
 * @export
 * @interface UIState
 */
export interface UIState {
    /**
     * 
     * @type {GamePhase}
     * @memberof UIState
     */
    phase: GamePhase;
    /**
     * 
     * @type {UIStateCode}
     * @memberof UIState
     */
    uiStateCode: UIStateCode;
}



/**
 * Check if a given object implements the UIState interface.
 */
export function instanceOfUIState(value: object): value is UIState {
    if (!('phase' in value) || value['phase'] === undefined) return false;
    if (!('uiStateCode' in value) || value['uiStateCode'] === undefined) return false;
    return true;
}

export function UIStateFromJSON(json: any): UIState {
    return UIStateFromJSONTyped(json, false);
}

export function UIStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UIState {
    if (json == null) {
        return json;
    }
    return {
        
        'phase': GamePhaseFromJSON(json['phase']),
        'uiStateCode': UIStateCodeFromJSON(json['uiStateCode']),
    };
}

  export function UIStateToJSON(json: any): UIState {
      return UIStateToJSONTyped(json, false);
  }

  export function UIStateToJSONTyped(value?: UIState | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phase': GamePhaseToJSON(value['phase']),
        'uiStateCode': UIStateCodeToJSON(value['uiStateCode']),
    };
}

