/* tslint:disable */
/* eslint-disable */
/**
 * Bodoge API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Card } from './Card';
import {
    CardFromJSON,
    CardFromJSONTyped,
    CardToJSON,
    CardToJSONTyped,
} from './Card';

/**
 * 
 * @export
 * @interface WsAndoAbility
 */
export interface WsAndoAbility {
    /**
     * 
     * @type {string}
     * @memberof WsAndoAbility
     */
    playerId: string;
    /**
     * 
     * @type {string}
     * @memberof WsAndoAbility
     */
    targetPlayerId: string;
    /**
     * 
     * @type {Card}
     * @memberof WsAndoAbility
     */
    card: Card;
}

/**
 * Check if a given object implements the WsAndoAbility interface.
 */
export function instanceOfWsAndoAbility(value: object): value is WsAndoAbility {
    if (!('playerId' in value) || value['playerId'] === undefined) return false;
    if (!('targetPlayerId' in value) || value['targetPlayerId'] === undefined) return false;
    if (!('card' in value) || value['card'] === undefined) return false;
    return true;
}

export function WsAndoAbilityFromJSON(json: any): WsAndoAbility {
    return WsAndoAbilityFromJSONTyped(json, false);
}

export function WsAndoAbilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): WsAndoAbility {
    if (json == null) {
        return json;
    }
    return {
        
        'playerId': json['playerId'],
        'targetPlayerId': json['targetPlayerId'],
        'card': CardFromJSON(json['card']),
    };
}

  export function WsAndoAbilityToJSON(json: any): WsAndoAbility {
      return WsAndoAbilityToJSONTyped(json, false);
  }

  export function WsAndoAbilityToJSONTyped(value?: WsAndoAbility | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playerId': value['playerId'],
        'targetPlayerId': value['targetPlayerId'],
        'card': CardToJSON(value['card']),
    };
}

