/* tslint:disable */
/* eslint-disable */
/**
 * Bodoge API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WsChoosePlayer
 */
export interface WsChoosePlayer {
    /**
     * 
     * @type {string}
     * @memberof WsChoosePlayer
     */
    playerId: string;
    /**
     * 
     * @type {string}
     * @memberof WsChoosePlayer
     */
    targetPlayerId: string;
    /**
     * 
     * @type {string}
     * @memberof WsChoosePlayer
     */
    effect: string;
}

/**
 * Check if a given object implements the WsChoosePlayer interface.
 */
export function instanceOfWsChoosePlayer(value: object): value is WsChoosePlayer {
    if (!('playerId' in value) || value['playerId'] === undefined) return false;
    if (!('targetPlayerId' in value) || value['targetPlayerId'] === undefined) return false;
    if (!('effect' in value) || value['effect'] === undefined) return false;
    return true;
}

export function WsChoosePlayerFromJSON(json: any): WsChoosePlayer {
    return WsChoosePlayerFromJSONTyped(json, false);
}

export function WsChoosePlayerFromJSONTyped(json: any, ignoreDiscriminator: boolean): WsChoosePlayer {
    if (json == null) {
        return json;
    }
    return {
        
        'playerId': json['playerId'],
        'targetPlayerId': json['targetPlayerId'],
        'effect': json['effect'],
    };
}

  export function WsChoosePlayerToJSON(json: any): WsChoosePlayer {
      return WsChoosePlayerToJSONTyped(json, false);
  }

  export function WsChoosePlayerToJSONTyped(value?: WsChoosePlayer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playerId': value['playerId'],
        'targetPlayerId': value['targetPlayerId'],
        'effect': value['effect'],
    };
}

