/* tslint:disable */
/* eslint-disable */
/**
 * Bodoge API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WsChooseHandFromClient
 */
export interface WsChooseHandFromClient {
    /**
     * 
     * @type {string}
     * @memberof WsChooseHandFromClient
     */
    playerId: string;
    /**
     * 
     * @type {string}
     * @memberof WsChooseHandFromClient
     */
    hand: string;
}

/**
 * Check if a given object implements the WsChooseHandFromClient interface.
 */
export function instanceOfWsChooseHandFromClient(value: object): value is WsChooseHandFromClient {
    if (!('playerId' in value) || value['playerId'] === undefined) return false;
    if (!('hand' in value) || value['hand'] === undefined) return false;
    return true;
}

export function WsChooseHandFromClientFromJSON(json: any): WsChooseHandFromClient {
    return WsChooseHandFromClientFromJSONTyped(json, false);
}

export function WsChooseHandFromClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): WsChooseHandFromClient {
    if (json == null) {
        return json;
    }
    return {
        
        'playerId': json['playerId'],
        'hand': json['hand'],
    };
}

  export function WsChooseHandFromClientToJSON(json: any): WsChooseHandFromClient {
      return WsChooseHandFromClientToJSONTyped(json, false);
  }

  export function WsChooseHandFromClientToJSONTyped(value?: WsChooseHandFromClient | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playerId': value['playerId'],
        'hand': value['hand'],
    };
}

