/* tslint:disable */
/* eslint-disable */
/**
 * Bodoge API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WsContinueToPlayFromClient
 */
export interface WsContinueToPlayFromClient {
    /**
     * 
     * @type {string}
     * @memberof WsContinueToPlayFromClient
     */
    playerId: string;
}

/**
 * Check if a given object implements the WsContinueToPlayFromClient interface.
 */
export function instanceOfWsContinueToPlayFromClient(value: object): value is WsContinueToPlayFromClient {
    if (!('playerId' in value) || value['playerId'] === undefined) return false;
    return true;
}

export function WsContinueToPlayFromClientFromJSON(json: any): WsContinueToPlayFromClient {
    return WsContinueToPlayFromClientFromJSONTyped(json, false);
}

export function WsContinueToPlayFromClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): WsContinueToPlayFromClient {
    if (json == null) {
        return json;
    }
    return {
        
        'playerId': json['playerId'],
    };
}

  export function WsContinueToPlayFromClientToJSON(json: any): WsContinueToPlayFromClient {
      return WsContinueToPlayFromClientToJSONTyped(json, false);
  }

  export function WsContinueToPlayFromClientToJSONTyped(value?: WsContinueToPlayFromClient | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playerId': value['playerId'],
    };
}

