/* tslint:disable */
/* eslint-disable */
/**
 * Bodoge API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WsFetch
 */
export interface WsFetch {
    /**
     * 
     * @type {string}
     * @memberof WsFetch
     */
    playerId: string;
    /**
     * 
     * @type {boolean}
     * @memberof WsFetch
     */
    isViewer?: boolean;
}

/**
 * Check if a given object implements the WsFetch interface.
 */
export function instanceOfWsFetch(value: object): value is WsFetch {
    if (!('playerId' in value) || value['playerId'] === undefined) return false;
    return true;
}

export function WsFetchFromJSON(json: any): WsFetch {
    return WsFetchFromJSONTyped(json, false);
}

export function WsFetchFromJSONTyped(json: any, ignoreDiscriminator: boolean): WsFetch {
    if (json == null) {
        return json;
    }
    return {
        
        'playerId': json['playerId'],
        'isViewer': json['isViewer'] == null ? undefined : json['isViewer'],
    };
}

  export function WsFetchToJSON(json: any): WsFetch {
      return WsFetchToJSONTyped(json, false);
  }

  export function WsFetchToJSONTyped(value?: WsFetch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playerId': value['playerId'],
        'isViewer': value['isViewer'],
    };
}

