/* tslint:disable */
/* eslint-disable */
/**
 * Bodoge API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WsMessage
 */
export interface WsMessage {
    /**
     * 
     * @type {any}
     * @memberof WsMessage
     */
    body: any | null;
    /**
     * 
     * @type {string}
     * @memberof WsMessage
     */
    messageType: string;
}

/**
 * Check if a given object implements the WsMessage interface.
 */
export function instanceOfWsMessage(value: object): value is WsMessage {
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('messageType' in value) || value['messageType'] === undefined) return false;
    return true;
}

export function WsMessageFromJSON(json: any): WsMessage {
    return WsMessageFromJSONTyped(json, false);
}

export function WsMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): WsMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
        'messageType': json['messageType'],
    };
}

  export function WsMessageToJSON(json: any): WsMessage {
      return WsMessageToJSONTyped(json, false);
  }

  export function WsMessageToJSONTyped(value?: WsMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
        'messageType': value['messageType'],
    };
}

