/* tslint:disable */
/* eslint-disable */
/**
 * Bodoge API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Card } from './Card';
import {
    CardFromJSON,
    CardFromJSONTyped,
    CardToJSON,
    CardToJSONTyped,
} from './Card';

/**
 * 
 * @export
 * @interface WsPowerUp
 */
export interface WsPowerUp {
    /**
     * 
     * @type {string}
     * @memberof WsPowerUp
     */
    playerId: string;
    /**
     * 
     * @type {Card}
     * @memberof WsPowerUp
     */
    card: Card;
}

/**
 * Check if a given object implements the WsPowerUp interface.
 */
export function instanceOfWsPowerUp(value: object): value is WsPowerUp {
    if (!('playerId' in value) || value['playerId'] === undefined) return false;
    if (!('card' in value) || value['card'] === undefined) return false;
    return true;
}

export function WsPowerUpFromJSON(json: any): WsPowerUp {
    return WsPowerUpFromJSONTyped(json, false);
}

export function WsPowerUpFromJSONTyped(json: any, ignoreDiscriminator: boolean): WsPowerUp {
    if (json == null) {
        return json;
    }
    return {
        
        'playerId': json['playerId'],
        'card': CardFromJSON(json['card']),
    };
}

  export function WsPowerUpToJSON(json: any): WsPowerUp {
      return WsPowerUpToJSONTyped(json, false);
  }

  export function WsPowerUpToJSONTyped(value?: WsPowerUp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playerId': value['playerId'],
        'card': CardToJSON(value['card']),
    };
}

