/* tslint:disable */
/* eslint-disable */
/**
 * Bodoge API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Destination } from './Destination';
import {
    DestinationFromJSON,
    DestinationFromJSONTyped,
    DestinationToJSON,
    DestinationToJSONTyped,
} from './Destination';
import type { Card } from './Card';
import {
    CardFromJSON,
    CardFromJSONTyped,
    CardToJSON,
    CardToJSONTyped,
} from './Card';

/**
 * 
 * @export
 * @interface WsReceiveCard
 */
export interface WsReceiveCard {
    /**
     * 
     * @type {string}
     * @memberof WsReceiveCard
     */
    playerId: string;
    /**
     * 
     * @type {Card}
     * @memberof WsReceiveCard
     */
    card?: Card;
    /**
     * 
     * @type {Destination}
     * @memberof WsReceiveCard
     */
    source: Destination;
    /**
     * 
     * @type {boolean}
     * @memberof WsReceiveCard
     */
    isSkip: boolean;
}



/**
 * Check if a given object implements the WsReceiveCard interface.
 */
export function instanceOfWsReceiveCard(value: object): value is WsReceiveCard {
    if (!('playerId' in value) || value['playerId'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('isSkip' in value) || value['isSkip'] === undefined) return false;
    return true;
}

export function WsReceiveCardFromJSON(json: any): WsReceiveCard {
    return WsReceiveCardFromJSONTyped(json, false);
}

export function WsReceiveCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): WsReceiveCard {
    if (json == null) {
        return json;
    }
    return {
        
        'playerId': json['playerId'],
        'card': json['card'] == null ? undefined : CardFromJSON(json['card']),
        'source': DestinationFromJSON(json['source']),
        'isSkip': json['isSkip'],
    };
}

  export function WsReceiveCardToJSON(json: any): WsReceiveCard {
      return WsReceiveCardToJSONTyped(json, false);
  }

  export function WsReceiveCardToJSONTyped(value?: WsReceiveCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playerId': value['playerId'],
        'card': CardToJSON(value['card']),
        'source': DestinationToJSON(value['source']),
        'isSkip': value['isSkip'],
    };
}

